### ISSUE TITLE
Progress tracker za minimalne requirementse labosa

### ISSUE THREAD

**Issue by jerzabek** [jerzabek/mobilni-uredaji-dataset#12]
Ovo su minimalni requirementsi koje moram zadovoljiti:

- [x] jednu **GET** krajnju točku za dohvaćanje cjelokupne kolekcije vaših podataka. (`GET /api/phones`)
- [x]  jednu **GET** krajnju točku za dohvaćanje pojedinačnog resursa iz kolekcije temeljem jedinstvenog identifikatora resursa. (`GET /api/phone/1`)
- [x]  barem tri dodatne **GET** krajnje točke po vlastitom odabiru. (`GET /api/processor/1`, `GET /api/company/1`, `GET /api/camera/1`)
- [x]  jednu **POST** krajnju točku za ubacivanje pojedinačnog resursa u kolekciju. (`POST /api/company`)
- [x]  jednu **PUT** krajnju točku kojom će se osvježiti elementi resursa. (`PUT /api/company/1`)
- [x]  jednu **DELETE** krajnju točku za brisanje pojedinog resursa iz kolekcije temeljem jedinstvenog identifikatora resursa (`DELETE /api/company/1`)
- [x] **GET** endpoint za OpenAPI dokumentaciju (valjda `GET /api/openapi` ili documentation ili nešto takvo)

**Comment by jerzabek** [comment]
Svi requirementsi za treću laboratorijsku vježbu zadovoljeni i deployani na https://or.jarza.cc/api/
